### ISSUE TITLE
set parameters 

### ISSUE THREAD

**Issue by naroberto** [vivekhsridhar/tracktor#13]
Hi Vivek, 
I am using tracktor to track fish. Anyhow the code often confuses the fish with some dark wall reflections and I was wondering how you go about calibrating the parameters block_size and scaling. Min and max area is very clear to me.
Here is a screenshot showing the problem. I currently run the code with 
-> block_size = 31
-> offset = 50 

Thanks for your help. 
Best 
Robert

![CaptureFish](https://user-images.githubusercontent.com/21307977/61134527-108f1780-a4c0-11e9-8893-57618a339d48.PNG)

**Comment by vivekhsridhar** [comment]
Dear Robert,

You'd need better lighing in your video recordings. Shadows are hard to deal withs since they provide similar contrast with the background. You could mask out the edges where the shadows are and try again but if you haven't gone all the way, I'd suggest refilming with more even lighting.

CHeers!
Vivek
